apiVersion: apps/v1
kind: Deployment
metadata:
  name: csm-caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csm
  template:
    metadata:
      labels:
        app: csm
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          ports:
            - containerPort: 8383
          volumeMounts:
            - name: csm-caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: csm-caddy-config
          configMap:
            name: csm-caddy-config
---
apiVersion: v1
kind: Service
metadata:
  name: csm-caddy-service
spec:
  type: LoadBalancer
  selector:
    app: csm
  ports:
    - name: csm-http
      protocol: TCP
      port: 8383
      targetPort: 8383
