apiVersion: apps/v1
kind: Deployment
metadata:
  name: csm-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csm-api
  template:
    metadata:
      labels:
        app: csm-api
    spec:
      containers:
        - name: csm-api
          image: gcr.io/citric-lead-450721-v2/silk-csm:1.0.3
          ports:
            - containerPort: 8383
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: "15"
              memory: "58Gi"
            requests:
              nvidia.com/gpu: 1
              cpu: "8"
              memory: "48Gi"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: csm-api-service
spec:
  selector:
    app: csm-api
  ports:
    - port: 8383
      targetPort: 8383
  type: ClusterIP
